'use client';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/context/ThemeContext';
import { BlogProvider } from '@/context/BlogContext';
import Header from '@/components/Header';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: "",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <BlogProvider>
            <Header />
            <main className="container mx-auto px-4 py-8">{children}</main>
          </BlogProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}